services:
  db:
    image: postgres:18.1-alpine3.22
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./config/.env.development
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    container_name: nestjs_auth_db_dev
    volumes:
      - ./postgres_data:/var/lib/postgresql

  cache:
    image: redis:8.4.0-alpine
    restart: always
    ports:
      - "6379:6379"
    container_name: cache_dev
    volumes:
      - ./redis_data:/data
    depends_on:
      - db

volumes:
  postgres_data:
  redis_data:
